---
engines:
  brakeman:
    enabled: true
    exclude_fingerprints:
      - 9e450b4277235e592c083dc95e4902a07537932fa4f1bfb631d7b2438066564d
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
    exclude_fingerprints:
    - 2819dac1dd742ddac6f76b0c08ca4913
    - 71fcf93df2ccca56752f8f847dffdb64
    - 77c153b9f89a5a231ac7681cd258c03f
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
    exclude_fingerprints:
      - f8e67af4417734ae7648d08baac41965
  eslint:
    enabled: true
    exclude_fingerprints:
    - 814c94af667ef24d78ad028d79f9daeb
    - 81f1db8cc66fe7d124f1ecde5904b4e5
  fixme:
    enabled: true
  rubocop:
    enabled: true
    exclude_fingerprints:
    - dafaed1c5f87439827acf59248ad24ab
    - dde1d5af6087a6c76a8d80e84eb82e07
    - 9f8b5e6463b88d2db01e92a459055f99
    - 470047cc9dd16445f5293f41cc75f6bf
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.css"
  - "**.coffee"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
exclude_paths:
- config/
- db/
- spec/