language: ruby
rvm:
  - 2.4.2
before_install:
  - gem update --system
  - gem --version
  - gem install bundler
cache: bundler
services:
  - postgresql
jobs: 
  include: 
    
    - stage: linter
      script: bundle exec rubocop
      
    - stage: security
      script: bundle exec brakeman -z
      
    - stage: tests
      before_script:
      - psql -c 'create database travis_ci_test;' -U postgres
      script: RAILS_ENV=test bundle exec rake --trace spec SPEC_OPTS="--tag ~pi_dependent:true"