language: ruby
rvm:
  - 2.4.2
before_install:
  - gem update --system
  - gem --version
services:
  - postgresql
  - redis
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec sidekiq
